CREATE TABLE IF NOT EXISTS todos_user(
    id SERIAL PRIMARY KEY,
    title varchar(255) NOT NULL,
    completed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_DATE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_DATE
);